runtime: python39
entrypoint: gunicorn -b :$PORT main:app --preload && python create_test_user.py
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 15
env_variables:
  CLOUD_SQL_CONNECTION_NAME: 'timesheet-data-290519:us-central1:tadashboard'
  DB_USER: 'root'
  DB_PASSWORD: 'juqjE4-xesgiw-pysdyw'
  DB_NAME: 'ta_dashboard_db'
  FLASK_ENV: 'production'
  FLASK_DEBUG: 'true'
