"""Added department column to User model

Revision ID: 83661b8312be
Revises: 9c58e3494129
Create Date: 2023-08-22 14:07:51.167752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83661b8312be'
down_revision = '9c58e3494129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('department')

    # ### end Alembic commands ###
