"""Add icon_class column to MenuItem model

Revision ID: 9c58e3494129
Revises: 2212c2e444e8
Create Date: 2023-07-25 17:05:55.390680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c58e3494129'
down_revision = '2212c2e444e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_class', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.drop_column('icon_class')

    # ### end Alembic commands ###
